version: "3"
services:
  springboot-app:
    image: springbooot-app
    restart: always
    build: ..
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Mihir@1611
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: grocery
      MYSQL_ROOT_PASSWORD: Mihir@1611
